name: telegram_log_sender
description: "A Flutter package for sending logs to a Telegram user via a bot"
version: 0.0.2
homepage: https://github.com/devituz/telegram_log_sender

environment:
  sdk: ^3.6.0
  flutter: ">=1.20.0"

dependencies:
  dio: ^5.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Information on the generic Dart part of this file:
# For more information, check the following page:
# https://dart.dev/tools/pub/pubspec

# Flutter-specific configurations:
flutter:
  plugin:
    platforms:
      android:
        package: com.devituz.telegram_log_sender
        pluginClass: TelegramLogSender

  # Example of how to add assets to your package:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, refer to:
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your package, you can use the "fonts" section:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For more information about fonts, check:
  # https://flutter.dev/to/font-from-package
